
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `location` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model location
 * 
 */
export type locationModel = runtime.Types.Result.DefaultSelection<Prisma.$locationPayload>

export type AggregateLocation = {
  _count: LocationCountAggregateOutputType | null
  _avg: LocationAvgAggregateOutputType | null
  _sum: LocationSumAggregateOutputType | null
  _min: LocationMinAggregateOutputType | null
  _max: LocationMaxAggregateOutputType | null
}

export type LocationAvgAggregateOutputType = {
  latitude: number | null
  longitude: number | null
}

export type LocationSumAggregateOutputType = {
  latitude: number | null
  longitude: number | null
}

export type LocationMinAggregateOutputType = {
  id: string | null
  latitude: number | null
  longitude: number | null
  local_time: Date | null
  create_date: Date | null
  update_date: Date | null
}

export type LocationMaxAggregateOutputType = {
  id: string | null
  latitude: number | null
  longitude: number | null
  local_time: Date | null
  create_date: Date | null
  update_date: Date | null
}

export type LocationCountAggregateOutputType = {
  id: number
  latitude: number
  longitude: number
  local_time: number
  create_date: number
  update_date: number
  _all: number
}


export type LocationAvgAggregateInputType = {
  latitude?: true
  longitude?: true
}

export type LocationSumAggregateInputType = {
  latitude?: true
  longitude?: true
}

export type LocationMinAggregateInputType = {
  id?: true
  latitude?: true
  longitude?: true
  local_time?: true
  create_date?: true
  update_date?: true
}

export type LocationMaxAggregateInputType = {
  id?: true
  latitude?: true
  longitude?: true
  local_time?: true
  create_date?: true
  update_date?: true
}

export type LocationCountAggregateInputType = {
  id?: true
  latitude?: true
  longitude?: true
  local_time?: true
  create_date?: true
  update_date?: true
  _all?: true
}

export type LocationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which location to aggregate.
   */
  where?: Prisma.locationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of locations to fetch.
   */
  orderBy?: Prisma.locationOrderByWithRelationInput | Prisma.locationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.locationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` locations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` locations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned locations
  **/
  _count?: true | LocationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LocationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LocationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LocationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LocationMaxAggregateInputType
}

export type GetLocationAggregateType<T extends LocationAggregateArgs> = {
      [P in keyof T & keyof AggregateLocation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLocation[P]>
    : Prisma.GetScalarType<T[P], AggregateLocation[P]>
}




export type locationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.locationWhereInput
  orderBy?: Prisma.locationOrderByWithAggregationInput | Prisma.locationOrderByWithAggregationInput[]
  by: Prisma.LocationScalarFieldEnum[] | Prisma.LocationScalarFieldEnum
  having?: Prisma.locationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LocationCountAggregateInputType | true
  _avg?: LocationAvgAggregateInputType
  _sum?: LocationSumAggregateInputType
  _min?: LocationMinAggregateInputType
  _max?: LocationMaxAggregateInputType
}

export type LocationGroupByOutputType = {
  id: string
  latitude: number
  longitude: number
  local_time: Date
  create_date: Date
  update_date: Date
  _count: LocationCountAggregateOutputType | null
  _avg: LocationAvgAggregateOutputType | null
  _sum: LocationSumAggregateOutputType | null
  _min: LocationMinAggregateOutputType | null
  _max: LocationMaxAggregateOutputType | null
}

export type GetLocationGroupByPayload<T extends locationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LocationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LocationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LocationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LocationGroupByOutputType[P]>
      }
    >
  >



export type locationWhereInput = {
  AND?: Prisma.locationWhereInput | Prisma.locationWhereInput[]
  OR?: Prisma.locationWhereInput[]
  NOT?: Prisma.locationWhereInput | Prisma.locationWhereInput[]
  id?: Prisma.StringFilter<"location"> | string
  latitude?: Prisma.FloatFilter<"location"> | number
  longitude?: Prisma.FloatFilter<"location"> | number
  local_time?: Prisma.DateTimeFilter<"location"> | Date | string
  create_date?: Prisma.DateTimeFilter<"location"> | Date | string
  update_date?: Prisma.DateTimeFilter<"location"> | Date | string
}

export type locationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  local_time?: Prisma.SortOrder
  create_date?: Prisma.SortOrder
  update_date?: Prisma.SortOrder
}

export type locationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.locationWhereInput | Prisma.locationWhereInput[]
  OR?: Prisma.locationWhereInput[]
  NOT?: Prisma.locationWhereInput | Prisma.locationWhereInput[]
  latitude?: Prisma.FloatFilter<"location"> | number
  longitude?: Prisma.FloatFilter<"location"> | number
  local_time?: Prisma.DateTimeFilter<"location"> | Date | string
  create_date?: Prisma.DateTimeFilter<"location"> | Date | string
  update_date?: Prisma.DateTimeFilter<"location"> | Date | string
}, "id">

export type locationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  local_time?: Prisma.SortOrder
  create_date?: Prisma.SortOrder
  update_date?: Prisma.SortOrder
  _count?: Prisma.locationCountOrderByAggregateInput
  _avg?: Prisma.locationAvgOrderByAggregateInput
  _max?: Prisma.locationMaxOrderByAggregateInput
  _min?: Prisma.locationMinOrderByAggregateInput
  _sum?: Prisma.locationSumOrderByAggregateInput
}

export type locationScalarWhereWithAggregatesInput = {
  AND?: Prisma.locationScalarWhereWithAggregatesInput | Prisma.locationScalarWhereWithAggregatesInput[]
  OR?: Prisma.locationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.locationScalarWhereWithAggregatesInput | Prisma.locationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"location"> | string
  latitude?: Prisma.FloatWithAggregatesFilter<"location"> | number
  longitude?: Prisma.FloatWithAggregatesFilter<"location"> | number
  local_time?: Prisma.DateTimeWithAggregatesFilter<"location"> | Date | string
  create_date?: Prisma.DateTimeWithAggregatesFilter<"location"> | Date | string
  update_date?: Prisma.DateTimeWithAggregatesFilter<"location"> | Date | string
}

export type locationCreateInput = {
  id: string
  latitude: number
  longitude: number
  local_time: Date | string
  create_date: Date | string
  update_date: Date | string
}

export type locationUncheckedCreateInput = {
  id: string
  latitude: number
  longitude: number
  local_time: Date | string
  create_date: Date | string
  update_date: Date | string
}

export type locationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  latitude?: Prisma.FloatFieldUpdateOperationsInput | number
  longitude?: Prisma.FloatFieldUpdateOperationsInput | number
  local_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  create_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  update_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type locationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  latitude?: Prisma.FloatFieldUpdateOperationsInput | number
  longitude?: Prisma.FloatFieldUpdateOperationsInput | number
  local_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  create_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  update_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type locationCreateManyInput = {
  id: string
  latitude: number
  longitude: number
  local_time: Date | string
  create_date: Date | string
  update_date: Date | string
}

export type locationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  latitude?: Prisma.FloatFieldUpdateOperationsInput | number
  longitude?: Prisma.FloatFieldUpdateOperationsInput | number
  local_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  create_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  update_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type locationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  latitude?: Prisma.FloatFieldUpdateOperationsInput | number
  longitude?: Prisma.FloatFieldUpdateOperationsInput | number
  local_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  create_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  update_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type locationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  local_time?: Prisma.SortOrder
  create_date?: Prisma.SortOrder
  update_date?: Prisma.SortOrder
}

export type locationAvgOrderByAggregateInput = {
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
}

export type locationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  local_time?: Prisma.SortOrder
  create_date?: Prisma.SortOrder
  update_date?: Prisma.SortOrder
}

export type locationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  local_time?: Prisma.SortOrder
  create_date?: Prisma.SortOrder
  update_date?: Prisma.SortOrder
}

export type locationSumOrderByAggregateInput = {
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type locationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  latitude?: boolean
  longitude?: boolean
  local_time?: boolean
  create_date?: boolean
  update_date?: boolean
}, ExtArgs["result"]["location"]>

export type locationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  latitude?: boolean
  longitude?: boolean
  local_time?: boolean
  create_date?: boolean
  update_date?: boolean
}, ExtArgs["result"]["location"]>

export type locationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  latitude?: boolean
  longitude?: boolean
  local_time?: boolean
  create_date?: boolean
  update_date?: boolean
}, ExtArgs["result"]["location"]>

export type locationSelectScalar = {
  id?: boolean
  latitude?: boolean
  longitude?: boolean
  local_time?: boolean
  create_date?: boolean
  update_date?: boolean
}

export type locationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "latitude" | "longitude" | "local_time" | "create_date" | "update_date", ExtArgs["result"]["location"]>

export type $locationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "location"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    latitude: number
    longitude: number
    local_time: Date
    create_date: Date
    update_date: Date
  }, ExtArgs["result"]["location"]>
  composites: {}
}

export type locationGetPayload<S extends boolean | null | undefined | locationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$locationPayload, S>

export type locationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<locationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LocationCountAggregateInputType | true
  }

export interface locationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['location'], meta: { name: 'location' } }
  /**
   * Find zero or one Location that matches the filter.
   * @param {locationFindUniqueArgs} args - Arguments to find a Location
   * @example
   * // Get one Location
   * const location = await prisma.location.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends locationFindUniqueArgs>(args: Prisma.SelectSubset<T, locationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__locationClient<runtime.Types.Result.GetResult<Prisma.$locationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Location that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {locationFindUniqueOrThrowArgs} args - Arguments to find a Location
   * @example
   * // Get one Location
   * const location = await prisma.location.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends locationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, locationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__locationClient<runtime.Types.Result.GetResult<Prisma.$locationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Location that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {locationFindFirstArgs} args - Arguments to find a Location
   * @example
   * // Get one Location
   * const location = await prisma.location.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends locationFindFirstArgs>(args?: Prisma.SelectSubset<T, locationFindFirstArgs<ExtArgs>>): Prisma.Prisma__locationClient<runtime.Types.Result.GetResult<Prisma.$locationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Location that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {locationFindFirstOrThrowArgs} args - Arguments to find a Location
   * @example
   * // Get one Location
   * const location = await prisma.location.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends locationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, locationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__locationClient<runtime.Types.Result.GetResult<Prisma.$locationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Locations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {locationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Locations
   * const locations = await prisma.location.findMany()
   * 
   * // Get first 10 Locations
   * const locations = await prisma.location.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const locationWithIdOnly = await prisma.location.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends locationFindManyArgs>(args?: Prisma.SelectSubset<T, locationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$locationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Location.
   * @param {locationCreateArgs} args - Arguments to create a Location.
   * @example
   * // Create one Location
   * const Location = await prisma.location.create({
   *   data: {
   *     // ... data to create a Location
   *   }
   * })
   * 
   */
  create<T extends locationCreateArgs>(args: Prisma.SelectSubset<T, locationCreateArgs<ExtArgs>>): Prisma.Prisma__locationClient<runtime.Types.Result.GetResult<Prisma.$locationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Locations.
   * @param {locationCreateManyArgs} args - Arguments to create many Locations.
   * @example
   * // Create many Locations
   * const location = await prisma.location.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends locationCreateManyArgs>(args?: Prisma.SelectSubset<T, locationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Locations and returns the data saved in the database.
   * @param {locationCreateManyAndReturnArgs} args - Arguments to create many Locations.
   * @example
   * // Create many Locations
   * const location = await prisma.location.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Locations and only return the `id`
   * const locationWithIdOnly = await prisma.location.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends locationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, locationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$locationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Location.
   * @param {locationDeleteArgs} args - Arguments to delete one Location.
   * @example
   * // Delete one Location
   * const Location = await prisma.location.delete({
   *   where: {
   *     // ... filter to delete one Location
   *   }
   * })
   * 
   */
  delete<T extends locationDeleteArgs>(args: Prisma.SelectSubset<T, locationDeleteArgs<ExtArgs>>): Prisma.Prisma__locationClient<runtime.Types.Result.GetResult<Prisma.$locationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Location.
   * @param {locationUpdateArgs} args - Arguments to update one Location.
   * @example
   * // Update one Location
   * const location = await prisma.location.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends locationUpdateArgs>(args: Prisma.SelectSubset<T, locationUpdateArgs<ExtArgs>>): Prisma.Prisma__locationClient<runtime.Types.Result.GetResult<Prisma.$locationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Locations.
   * @param {locationDeleteManyArgs} args - Arguments to filter Locations to delete.
   * @example
   * // Delete a few Locations
   * const { count } = await prisma.location.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends locationDeleteManyArgs>(args?: Prisma.SelectSubset<T, locationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Locations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {locationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Locations
   * const location = await prisma.location.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends locationUpdateManyArgs>(args: Prisma.SelectSubset<T, locationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Locations and returns the data updated in the database.
   * @param {locationUpdateManyAndReturnArgs} args - Arguments to update many Locations.
   * @example
   * // Update many Locations
   * const location = await prisma.location.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Locations and only return the `id`
   * const locationWithIdOnly = await prisma.location.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends locationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, locationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$locationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Location.
   * @param {locationUpsertArgs} args - Arguments to update or create a Location.
   * @example
   * // Update or create a Location
   * const location = await prisma.location.upsert({
   *   create: {
   *     // ... data to create a Location
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Location we want to update
   *   }
   * })
   */
  upsert<T extends locationUpsertArgs>(args: Prisma.SelectSubset<T, locationUpsertArgs<ExtArgs>>): Prisma.Prisma__locationClient<runtime.Types.Result.GetResult<Prisma.$locationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Locations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {locationCountArgs} args - Arguments to filter Locations to count.
   * @example
   * // Count the number of Locations
   * const count = await prisma.location.count({
   *   where: {
   *     // ... the filter for the Locations we want to count
   *   }
   * })
  **/
  count<T extends locationCountArgs>(
    args?: Prisma.Subset<T, locationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LocationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Location.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LocationAggregateArgs>(args: Prisma.Subset<T, LocationAggregateArgs>): Prisma.PrismaPromise<GetLocationAggregateType<T>>

  /**
   * Group by Location.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {locationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends locationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: locationGroupByArgs['orderBy'] }
      : { orderBy?: locationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, locationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLocationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the location model
 */
readonly fields: locationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for location.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__locationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the location model
 */
export interface locationFieldRefs {
  readonly id: Prisma.FieldRef<"location", 'String'>
  readonly latitude: Prisma.FieldRef<"location", 'Float'>
  readonly longitude: Prisma.FieldRef<"location", 'Float'>
  readonly local_time: Prisma.FieldRef<"location", 'DateTime'>
  readonly create_date: Prisma.FieldRef<"location", 'DateTime'>
  readonly update_date: Prisma.FieldRef<"location", 'DateTime'>
}
    

// Custom InputTypes
/**
 * location findUnique
 */
export type locationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the location
   */
  select?: Prisma.locationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the location
   */
  omit?: Prisma.locationOmit<ExtArgs> | null
  /**
   * Filter, which location to fetch.
   */
  where: Prisma.locationWhereUniqueInput
}

/**
 * location findUniqueOrThrow
 */
export type locationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the location
   */
  select?: Prisma.locationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the location
   */
  omit?: Prisma.locationOmit<ExtArgs> | null
  /**
   * Filter, which location to fetch.
   */
  where: Prisma.locationWhereUniqueInput
}

/**
 * location findFirst
 */
export type locationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the location
   */
  select?: Prisma.locationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the location
   */
  omit?: Prisma.locationOmit<ExtArgs> | null
  /**
   * Filter, which location to fetch.
   */
  where?: Prisma.locationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of locations to fetch.
   */
  orderBy?: Prisma.locationOrderByWithRelationInput | Prisma.locationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for locations.
   */
  cursor?: Prisma.locationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` locations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` locations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of locations.
   */
  distinct?: Prisma.LocationScalarFieldEnum | Prisma.LocationScalarFieldEnum[]
}

/**
 * location findFirstOrThrow
 */
export type locationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the location
   */
  select?: Prisma.locationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the location
   */
  omit?: Prisma.locationOmit<ExtArgs> | null
  /**
   * Filter, which location to fetch.
   */
  where?: Prisma.locationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of locations to fetch.
   */
  orderBy?: Prisma.locationOrderByWithRelationInput | Prisma.locationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for locations.
   */
  cursor?: Prisma.locationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` locations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` locations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of locations.
   */
  distinct?: Prisma.LocationScalarFieldEnum | Prisma.LocationScalarFieldEnum[]
}

/**
 * location findMany
 */
export type locationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the location
   */
  select?: Prisma.locationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the location
   */
  omit?: Prisma.locationOmit<ExtArgs> | null
  /**
   * Filter, which locations to fetch.
   */
  where?: Prisma.locationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of locations to fetch.
   */
  orderBy?: Prisma.locationOrderByWithRelationInput | Prisma.locationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing locations.
   */
  cursor?: Prisma.locationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` locations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` locations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of locations.
   */
  distinct?: Prisma.LocationScalarFieldEnum | Prisma.LocationScalarFieldEnum[]
}

/**
 * location create
 */
export type locationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the location
   */
  select?: Prisma.locationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the location
   */
  omit?: Prisma.locationOmit<ExtArgs> | null
  /**
   * The data needed to create a location.
   */
  data: Prisma.XOR<Prisma.locationCreateInput, Prisma.locationUncheckedCreateInput>
}

/**
 * location createMany
 */
export type locationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many locations.
   */
  data: Prisma.locationCreateManyInput | Prisma.locationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * location createManyAndReturn
 */
export type locationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the location
   */
  select?: Prisma.locationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the location
   */
  omit?: Prisma.locationOmit<ExtArgs> | null
  /**
   * The data used to create many locations.
   */
  data: Prisma.locationCreateManyInput | Prisma.locationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * location update
 */
export type locationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the location
   */
  select?: Prisma.locationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the location
   */
  omit?: Prisma.locationOmit<ExtArgs> | null
  /**
   * The data needed to update a location.
   */
  data: Prisma.XOR<Prisma.locationUpdateInput, Prisma.locationUncheckedUpdateInput>
  /**
   * Choose, which location to update.
   */
  where: Prisma.locationWhereUniqueInput
}

/**
 * location updateMany
 */
export type locationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update locations.
   */
  data: Prisma.XOR<Prisma.locationUpdateManyMutationInput, Prisma.locationUncheckedUpdateManyInput>
  /**
   * Filter which locations to update
   */
  where?: Prisma.locationWhereInput
  /**
   * Limit how many locations to update.
   */
  limit?: number
}

/**
 * location updateManyAndReturn
 */
export type locationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the location
   */
  select?: Prisma.locationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the location
   */
  omit?: Prisma.locationOmit<ExtArgs> | null
  /**
   * The data used to update locations.
   */
  data: Prisma.XOR<Prisma.locationUpdateManyMutationInput, Prisma.locationUncheckedUpdateManyInput>
  /**
   * Filter which locations to update
   */
  where?: Prisma.locationWhereInput
  /**
   * Limit how many locations to update.
   */
  limit?: number
}

/**
 * location upsert
 */
export type locationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the location
   */
  select?: Prisma.locationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the location
   */
  omit?: Prisma.locationOmit<ExtArgs> | null
  /**
   * The filter to search for the location to update in case it exists.
   */
  where: Prisma.locationWhereUniqueInput
  /**
   * In case the location found by the `where` argument doesn't exist, create a new location with this data.
   */
  create: Prisma.XOR<Prisma.locationCreateInput, Prisma.locationUncheckedCreateInput>
  /**
   * In case the location was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.locationUpdateInput, Prisma.locationUncheckedUpdateInput>
}

/**
 * location delete
 */
export type locationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the location
   */
  select?: Prisma.locationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the location
   */
  omit?: Prisma.locationOmit<ExtArgs> | null
  /**
   * Filter which location to delete.
   */
  where: Prisma.locationWhereUniqueInput
}

/**
 * location deleteMany
 */
export type locationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which locations to delete
   */
  where?: Prisma.locationWhereInput
  /**
   * Limit how many locations to delete.
   */
  limit?: number
}

/**
 * location without action
 */
export type locationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the location
   */
  select?: Prisma.locationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the location
   */
  omit?: Prisma.locationOmit<ExtArgs> | null
}
